/**
 * CLI: generate artifacts. Requires --out-dir or --to.
 * Example: pnpm --filter @ssv/schemas generate --out-dir packages/frontend/src
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(__dirname, "..");

function findRepoRoot(start: string): string {
  let dir = start;
  for (;;) {
    if (fs.existsSync(path.join(dir, "pnpm-workspace.yaml"))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return process.cwd();
    dir = parent;
  }
}

const REPO_ROOT = findRepoRoot(PACKAGE_ROOT);
const DATA_PATH = path.join(PACKAGE_ROOT, "data", "structured_output_groups.json");

const USAGE = `
Usage: generate --out-dir <path>   (or --to <path>)

  --out-dir <path>   Directory to write generated artifacts. Required.
  --to <path>        Alias for --out-dir.

Writes under the given path:
  - data/structured_output_groups.generated.json
  - types/structuredOutputGroups.generated.ts
`;

function parseArgs(): string | null {
  const args = process.argv.slice(2);
  for (let i = 0; i < args.length; i++) {
    if ((args[i] === "--out-dir" || args[i] === "--to") && args[i + 1]) {
      return path.resolve(REPO_ROOT, args[i + 1]);
    }
  }
  return null;
}

function main(): void {
  const outDir = parseArgs();
  if (!outDir) {
    console.error(USAGE);
    process.exit(1);
  }

  if (!fs.existsSync(DATA_PATH)) {
    console.error(`Data not found: ${DATA_PATH}`);
    process.exit(1);
  }

  const groupsJson = fs.readFileSync(DATA_PATH, "utf-8");
  const typesPath = path.join(__dirname, "types-template.ts");
  const typesContent = fs.readFileSync(typesPath, "utf-8");
  const generatedTypesContent = typesContent.replace(
    "Generated from @ssv/schemas. Do not edit by hand.",
    "Generated by @ssv/schemas. Do not edit by hand."
  );

  const dataDir = path.join(outDir, "data");
  const typesDir = path.join(outDir, "types");
  fs.mkdirSync(dataDir, { recursive: true });
  fs.mkdirSync(typesDir, { recursive: true });

  const jsonOutPath = path.join(dataDir, "structured_output_groups.generated.json");
  const tsOutPath = path.join(typesDir, "structuredOutputGroups.generated.ts");

  fs.writeFileSync(jsonOutPath, groupsJson, "utf-8");
  fs.writeFileSync(tsOutPath, generatedTypesContent, "utf-8");

  console.log(`Wrote ${jsonOutPath}`);
  console.log(`Wrote ${tsOutPath}`);
}

main();
